# Generated by Django 5.0.6 on 2024-06-03 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cod_dane', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
                ('icono', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TipoCuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de Cuenta Bancaria',
                'verbose_name_plural': 'Tipos de cuenta bancaria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('cod', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('cod_dane', models.CharField(max_length=5, unique=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.departamento')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('orden', models.IntegerField()),
                ('icono', models.CharField(max_length=50)),
                ('enlace', models.CharField(max_length=128)),
                ('favorito', models.BooleanField(default=False)),
                ('variable', models.CharField(max_length=20)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.menu')),
            ],
            options={
                'verbose_name': 'Submenú',
                'verbose_name_plural': 'submenús',
                'ordering': ['orden'],
            },
        ),
    ]
