# Generated by Django 5.0.6 on 2024-06-03 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_compra', models.DateField()),
                ('num_factura_proveedor', models.CharField(blank=True, max_length=30, null=True)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vence', models.DateField()),
                ('fecha_recibido', models.DateField()),
                ('nota', models.CharField(blank=True, max_length=250, null=True)),
                ('forma_pago', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseapp.formapago')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compras.estadocompra')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CompraDetalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('paquetes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidades', models.IntegerField(default=1)),
                ('valor_paquete', models.FloatField()),
                ('descuento_pre_iva', models.FloatField(default=0, verbose_name='Desc pre')),
                ('descuento_pos_iva', models.FloatField(default=0, verbose_name='Desc pos')),
                ('iva', models.IntegerField(default=0)),
                ('flete', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.CharField(blank=True, max_length=250, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'verbose_name': 'CompraDetalle',
                'verbose_name_plural': 'CompraDetalles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('barrio', models.CharField(blank=True, max_length=150, null=True)),
                ('ubicacion_GPS', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('condiciones_credito', models.CharField(blank=True, max_length=256, null=True)),
                ('condiciones_descuento', models.CharField(blank=True, max_length=256, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.ciudad')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.tipodocumento')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_pago', models.DateField()),
                ('valor_pago', models.FloatField()),
                ('nota', models.CharField(blank=True, max_length=250, null=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compra')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.formapago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'pagoCompra',
                'verbose_name_plural': 'PagosCompra',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor'),
        ),
    ]
